### ISSUE TITLE
Huge logo file. 

### ISSUE THREAD

**Issue by dietmarw** [USN-latex/Beamer-Template#2]
The HSN logo file in this repo is **HUGE**. If you like I can replace it with the tiny version from my repo: 
https://github.com/dietmarw/USN-LaTeX/tree/master/logos

Your logo is 552kB, the one from my rep 5kB with no loss in quality.

**Comment by gitEO** [comment]
Hi Dietmar,


Go ahead, no problem.


/Eirik/

________________________________
Frå: Dietmar Winkler <notifications@github.com>
Sendt: 12. januar 2017 16:34:34
Til: USN-latex/Beamer-Template
Kopi: Subscribed
Emne: [USN-latex/Beamer-Template] Huge logo file. (#2)


The HSN logo file in this repo is HUGE. If you like I can replace it with the tiny version from my repo:
https://github.com/dietmarw/USN-LaTeX/tree/master/logos

Your logo is 552kB, the one from my rep 5kB with no loss in quality.

-

**Comment by dietmarw** [comment]
No reaction on the PR and HSN logo is no longer relevant.
